### ISSUE TITLE
Add persistent data during background process tasks to be used later on completion

### ISSUE THREAD

**Issue by danielpowney** [deliciousbrains/wp-background-processing#31] opened 2017-03-04 10:25 UTC
Similar to #9 , I  need to add persistent data during tasks in the background process, so by the time the background process has completed, I can then do something with the persistent data.

**Comment by dskvr** [comment] 2017-04-10 16:51
Could this not be accomplished with the following pattern?

`class WP_Example_Process extends WP_Background_Process {

	/**
	 * @var string
	 */
	protected $action = 'example_process';
	protected $persisted_data;

	/**
	 * Task
	 *
	 * Override this method to perform any actions required on each
	 * queue item. Return the modified item for further processing
	 * in the next pass through. Or, return false to remove the
	 * item from the queue.
	 *
	 * @param mixed $item Queue item to iterate over
	 *
	 * @return mixed
	 */
	protected function task( $item ) {
		// Actions to perform
                $this->$persisted_data = true;
		return false;
	}

	/**
	 * Complete
	 *
	 * Override if applicable, but ensure that the below actions are
	 * performed, or, call parent::complete().
	 */
	protected function complete() {
		parent::complete();
                echo ($this->$persisted_data) ? "it persisted" : "hmmmm didn't persist :/";
		// Show notice to user or perform some other arbitrary task...
	}

}`

**Comment by GigiSan** [comment] 2018-08-02 10:37
I have the same problem.

@dskvr the problem is, if the queue if split into more dispatches due to memory/time limit, all property of the WP_Background_Process instance are lost.

If you set the persistent data at each item you might still have them at complete(), but if you set it at construction for example, you'll lose it at the 2nd dispatch if more than one is needed.

**Comment by ianmjones** [comment] 2023-04-11 16:47
Closing as duplicate of #9.

**Closed by ianmjones** 2023-04-11 16:47 UTC
