### ISSUE TITLE
Have to declare handle_cron_healthcheck() for it to process

### ISSUE THREAD

**Issue by calebsmithdev** [deliciousbrains/wp-background-processing#34] opened 2017-04-02 23:58 UTC
I've been having some issues with the Background process calling handle and activating the cron schedules needed for the fallback. Right now, I am utilizing something I saw in WooCommerce to force a healthcheck, which will start the handle process. I have also hooked that into the heartbeat function to continue polling for background processes, in the event the original timesout. [This code ](https://gitlab.com/limelight-marketing/llm-hubspot-blog-import/blob/4bbfe2a2167bffc8e6377fcbacdee31dca721513/src/Save.php#L39)starts the process, and[ this code](https://gitlab.com/limelight-marketing/llm-hubspot-blog-import/blob/4bbfe2a2167bffc8e6377fcbacdee31dca721513/src/Save.php#L39) is where I declare the handle_cron_healthcheck().

Is there a better way to make sure the background process has started? I want this to be pretty painless, from a user perspective, but I also want to make sure I understand what I am doing! 

Really appreciate the help and for creating this awesome batch of code! I was really bummed when I moved from a Laravel project to a WP project and lost my queue process.

**Comment by dskvr** [comment] 2017-04-11 10:40
@Failcookie accidentally published the same link twice, the second link in his issue was intended to link to [this line](https://gitlab.com/limelight-marketing/llm-hubspot-blog-import/blob/4bbfe2a2167bffc8e6377fcbacdee31dca721513/src/Save.php#L132)

**Comment by leewillis77** [comment] 2017-06-23 10:14
Not sure if it's relevant here - however it seems that you can get issues with the heartbeat getting called in certain cases:

- If your job classes get instantiated *after* the cron_schedules filter has fired [In which case the frequency doesn't get registered so the queueing of the healthcheck fails]

- You dispatch your queue *before* the cron_schedules filter has fired [In which case the frequency hasn't been registered so the queueing of the healthcheck fails]

- You don't instantiate the job classes on every request [for example you only instantiate them on is_admin(), or ! is_admin()]. In which case your class might not exist when cron fires.

I've hit all three of these on a project - although it's legacy code and is a bit of a rats nest of timing and dependencies so some of the above may be down to that in part. May help you though!

**Comment by derchecker07** [comment] 2022-12-24 17:51
> If your job classes get instantiated after the cron_schedules filter has fired [In which case the frequency doesn't get registered so the queueing of the healthcheck fails]

@leewillis77 After multiple hours of trial and error, this part of your comment finally helped me fix my issue. I was instantiating my background-process-class only when the user clicked a specific button in the WP Admin UI and, as it turns out, this was way too late. 
Moving the instantiation to the "plugins_loaded" hook solved my issue - thank you very much! 🎉

**Comment by ianmjones** [comment] 2023-04-11 16:51
Closing ancient issue. :smile:

**Closed by ianmjones** 2023-04-11 16:51 UTC
